{% set name = "spdx-tools" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spdx-tools-{{ version }}.tar.gz
  sha256: aea4ac9c2c375e7f439b1cef5ff32ef34914c083de0f61e08ed67cd3d9deb2a9

build:
  entry_points:
    - pyspdxtools = spdx_tools.spdx.clitools.pyspdxtools:main
    - pyspdxtools3 = spdx_tools.spdx3.clitools.pyspdxtools3:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.2
    - setuptools-scm >=3.4.3
    - pip
  run:
    - python >=3.7
    - click
    - pyyaml
    - xmltodict
    - rdflib
    - beartype
    - uritools
    - license-expression
    - ply
    - semantic_version

test:
  imports:
    - spdx_tools
  commands:
    - pip check
    - pyspdxtools --help
    - pyspdxtools3 --help
  requires:
    - pip

about:
  home: https://github.com/spdx/tools-python
  summary: SPDX parser and tools.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nick-harmening
    - borchero
